// Code generated by counterfeiter. DO NOT EDIT.
package vmfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-cli/v7/deployment/manifest"
	"github.com/cloudfoundry/bosh-cli/v7/deployment/vm"
	"github.com/cloudfoundry/bosh-cli/v7/stemcell"
)

type FakeManager struct {
	CreateStub        func(stemcell.CloudStemcell, manifest.Manifest, []string) (vm.VM, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 stemcell.CloudStemcell
		arg2 manifest.Manifest
		arg3 []string
	}
	createReturns struct {
		result1 vm.VM
		result2 error
	}
	createReturnsOnCall map[int]struct {
		result1 vm.VM
		result2 error
	}
	FindCurrentStub        func() (vm.VM, bool, error)
	findCurrentMutex       sync.RWMutex
	findCurrentArgsForCall []struct {
	}
	findCurrentReturns struct {
		result1 vm.VM
		result2 bool
		result3 error
	}
	findCurrentReturnsOnCall map[int]struct {
		result1 vm.VM
		result2 bool
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeManager) Create(arg1 stemcell.CloudStemcell, arg2 manifest.Manifest, arg3 []string) (vm.VM, error) {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 stemcell.CloudStemcell
		arg2 manifest.Manifest
		arg3 []string
	}{arg1, arg2, arg3Copy})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2, arg3Copy})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeManager) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeManager) CreateCalls(stub func(stemcell.CloudStemcell, manifest.Manifest, []string) (vm.VM, error)) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeManager) CreateArgsForCall(i int) (stemcell.CloudStemcell, manifest.Manifest, []string) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeManager) CreateReturns(result1 vm.VM, result2 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 vm.VM
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) CreateReturnsOnCall(i int, result1 vm.VM, result2 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 vm.VM
			result2 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 vm.VM
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) FindCurrent() (vm.VM, bool, error) {
	fake.findCurrentMutex.Lock()
	ret, specificReturn := fake.findCurrentReturnsOnCall[len(fake.findCurrentArgsForCall)]
	fake.findCurrentArgsForCall = append(fake.findCurrentArgsForCall, struct {
	}{})
	stub := fake.FindCurrentStub
	fakeReturns := fake.findCurrentReturns
	fake.recordInvocation("FindCurrent", []interface{}{})
	fake.findCurrentMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeManager) FindCurrentCallCount() int {
	fake.findCurrentMutex.RLock()
	defer fake.findCurrentMutex.RUnlock()
	return len(fake.findCurrentArgsForCall)
}

func (fake *FakeManager) FindCurrentCalls(stub func() (vm.VM, bool, error)) {
	fake.findCurrentMutex.Lock()
	defer fake.findCurrentMutex.Unlock()
	fake.FindCurrentStub = stub
}

func (fake *FakeManager) FindCurrentReturns(result1 vm.VM, result2 bool, result3 error) {
	fake.findCurrentMutex.Lock()
	defer fake.findCurrentMutex.Unlock()
	fake.FindCurrentStub = nil
	fake.findCurrentReturns = struct {
		result1 vm.VM
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeManager) FindCurrentReturnsOnCall(i int, result1 vm.VM, result2 bool, result3 error) {
	fake.findCurrentMutex.Lock()
	defer fake.findCurrentMutex.Unlock()
	fake.FindCurrentStub = nil
	if fake.findCurrentReturnsOnCall == nil {
		fake.findCurrentReturnsOnCall = make(map[int]struct {
			result1 vm.VM
			result2 bool
			result3 error
		})
	}
	fake.findCurrentReturnsOnCall[i] = struct {
		result1 vm.VM
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ vm.Manager = new(FakeManager)
