// Code generated by counterfeiter. DO NOT EDIT.
package configfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-cli/v7/config"
)

type FakeStemcellRepo struct {
	AllStub        func() ([]config.StemcellRecord, error)
	allMutex       sync.RWMutex
	allArgsForCall []struct {
	}
	allReturns struct {
		result1 []config.StemcellRecord
		result2 error
	}
	allReturnsOnCall map[int]struct {
		result1 []config.StemcellRecord
		result2 error
	}
	ClearCurrentStub        func() error
	clearCurrentMutex       sync.RWMutex
	clearCurrentArgsForCall []struct {
	}
	clearCurrentReturns struct {
		result1 error
	}
	clearCurrentReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteStub        func(config.StemcellRecord) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 config.StemcellRecord
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	FindStub        func(string, string) (config.StemcellRecord, bool, error)
	findMutex       sync.RWMutex
	findArgsForCall []struct {
		arg1 string
		arg2 string
	}
	findReturns struct {
		result1 config.StemcellRecord
		result2 bool
		result3 error
	}
	findReturnsOnCall map[int]struct {
		result1 config.StemcellRecord
		result2 bool
		result3 error
	}
	FindCurrentStub        func() (config.StemcellRecord, bool, error)
	findCurrentMutex       sync.RWMutex
	findCurrentArgsForCall []struct {
	}
	findCurrentReturns struct {
		result1 config.StemcellRecord
		result2 bool
		result3 error
	}
	findCurrentReturnsOnCall map[int]struct {
		result1 config.StemcellRecord
		result2 bool
		result3 error
	}
	SaveStub        func(string, string, string, int) (config.StemcellRecord, error)
	saveMutex       sync.RWMutex
	saveArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 int
	}
	saveReturns struct {
		result1 config.StemcellRecord
		result2 error
	}
	saveReturnsOnCall map[int]struct {
		result1 config.StemcellRecord
		result2 error
	}
	UpdateCurrentStub        func(string) error
	updateCurrentMutex       sync.RWMutex
	updateCurrentArgsForCall []struct {
		arg1 string
	}
	updateCurrentReturns struct {
		result1 error
	}
	updateCurrentReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStemcellRepo) All() ([]config.StemcellRecord, error) {
	fake.allMutex.Lock()
	ret, specificReturn := fake.allReturnsOnCall[len(fake.allArgsForCall)]
	fake.allArgsForCall = append(fake.allArgsForCall, struct {
	}{})
	stub := fake.AllStub
	fakeReturns := fake.allReturns
	fake.recordInvocation("All", []interface{}{})
	fake.allMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStemcellRepo) AllCallCount() int {
	fake.allMutex.RLock()
	defer fake.allMutex.RUnlock()
	return len(fake.allArgsForCall)
}

func (fake *FakeStemcellRepo) AllCalls(stub func() ([]config.StemcellRecord, error)) {
	fake.allMutex.Lock()
	defer fake.allMutex.Unlock()
	fake.AllStub = stub
}

func (fake *FakeStemcellRepo) AllReturns(result1 []config.StemcellRecord, result2 error) {
	fake.allMutex.Lock()
	defer fake.allMutex.Unlock()
	fake.AllStub = nil
	fake.allReturns = struct {
		result1 []config.StemcellRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeStemcellRepo) AllReturnsOnCall(i int, result1 []config.StemcellRecord, result2 error) {
	fake.allMutex.Lock()
	defer fake.allMutex.Unlock()
	fake.AllStub = nil
	if fake.allReturnsOnCall == nil {
		fake.allReturnsOnCall = make(map[int]struct {
			result1 []config.StemcellRecord
			result2 error
		})
	}
	fake.allReturnsOnCall[i] = struct {
		result1 []config.StemcellRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeStemcellRepo) ClearCurrent() error {
	fake.clearCurrentMutex.Lock()
	ret, specificReturn := fake.clearCurrentReturnsOnCall[len(fake.clearCurrentArgsForCall)]
	fake.clearCurrentArgsForCall = append(fake.clearCurrentArgsForCall, struct {
	}{})
	stub := fake.ClearCurrentStub
	fakeReturns := fake.clearCurrentReturns
	fake.recordInvocation("ClearCurrent", []interface{}{})
	fake.clearCurrentMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStemcellRepo) ClearCurrentCallCount() int {
	fake.clearCurrentMutex.RLock()
	defer fake.clearCurrentMutex.RUnlock()
	return len(fake.clearCurrentArgsForCall)
}

func (fake *FakeStemcellRepo) ClearCurrentCalls(stub func() error) {
	fake.clearCurrentMutex.Lock()
	defer fake.clearCurrentMutex.Unlock()
	fake.ClearCurrentStub = stub
}

func (fake *FakeStemcellRepo) ClearCurrentReturns(result1 error) {
	fake.clearCurrentMutex.Lock()
	defer fake.clearCurrentMutex.Unlock()
	fake.ClearCurrentStub = nil
	fake.clearCurrentReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStemcellRepo) ClearCurrentReturnsOnCall(i int, result1 error) {
	fake.clearCurrentMutex.Lock()
	defer fake.clearCurrentMutex.Unlock()
	fake.ClearCurrentStub = nil
	if fake.clearCurrentReturnsOnCall == nil {
		fake.clearCurrentReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.clearCurrentReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStemcellRepo) Delete(arg1 config.StemcellRecord) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 config.StemcellRecord
	}{arg1})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStemcellRepo) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeStemcellRepo) DeleteCalls(stub func(config.StemcellRecord) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeStemcellRepo) DeleteArgsForCall(i int) config.StemcellRecord {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStemcellRepo) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStemcellRepo) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStemcellRepo) Find(arg1 string, arg2 string) (config.StemcellRecord, bool, error) {
	fake.findMutex.Lock()
	ret, specificReturn := fake.findReturnsOnCall[len(fake.findArgsForCall)]
	fake.findArgsForCall = append(fake.findArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.FindStub
	fakeReturns := fake.findReturns
	fake.recordInvocation("Find", []interface{}{arg1, arg2})
	fake.findMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeStemcellRepo) FindCallCount() int {
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	return len(fake.findArgsForCall)
}

func (fake *FakeStemcellRepo) FindCalls(stub func(string, string) (config.StemcellRecord, bool, error)) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = stub
}

func (fake *FakeStemcellRepo) FindArgsForCall(i int) (string, string) {
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	argsForCall := fake.findArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStemcellRepo) FindReturns(result1 config.StemcellRecord, result2 bool, result3 error) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = nil
	fake.findReturns = struct {
		result1 config.StemcellRecord
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeStemcellRepo) FindReturnsOnCall(i int, result1 config.StemcellRecord, result2 bool, result3 error) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = nil
	if fake.findReturnsOnCall == nil {
		fake.findReturnsOnCall = make(map[int]struct {
			result1 config.StemcellRecord
			result2 bool
			result3 error
		})
	}
	fake.findReturnsOnCall[i] = struct {
		result1 config.StemcellRecord
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeStemcellRepo) FindCurrent() (config.StemcellRecord, bool, error) {
	fake.findCurrentMutex.Lock()
	ret, specificReturn := fake.findCurrentReturnsOnCall[len(fake.findCurrentArgsForCall)]
	fake.findCurrentArgsForCall = append(fake.findCurrentArgsForCall, struct {
	}{})
	stub := fake.FindCurrentStub
	fakeReturns := fake.findCurrentReturns
	fake.recordInvocation("FindCurrent", []interface{}{})
	fake.findCurrentMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeStemcellRepo) FindCurrentCallCount() int {
	fake.findCurrentMutex.RLock()
	defer fake.findCurrentMutex.RUnlock()
	return len(fake.findCurrentArgsForCall)
}

func (fake *FakeStemcellRepo) FindCurrentCalls(stub func() (config.StemcellRecord, bool, error)) {
	fake.findCurrentMutex.Lock()
	defer fake.findCurrentMutex.Unlock()
	fake.FindCurrentStub = stub
}

func (fake *FakeStemcellRepo) FindCurrentReturns(result1 config.StemcellRecord, result2 bool, result3 error) {
	fake.findCurrentMutex.Lock()
	defer fake.findCurrentMutex.Unlock()
	fake.FindCurrentStub = nil
	fake.findCurrentReturns = struct {
		result1 config.StemcellRecord
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeStemcellRepo) FindCurrentReturnsOnCall(i int, result1 config.StemcellRecord, result2 bool, result3 error) {
	fake.findCurrentMutex.Lock()
	defer fake.findCurrentMutex.Unlock()
	fake.FindCurrentStub = nil
	if fake.findCurrentReturnsOnCall == nil {
		fake.findCurrentReturnsOnCall = make(map[int]struct {
			result1 config.StemcellRecord
			result2 bool
			result3 error
		})
	}
	fake.findCurrentReturnsOnCall[i] = struct {
		result1 config.StemcellRecord
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeStemcellRepo) Save(arg1 string, arg2 string, arg3 string, arg4 int) (config.StemcellRecord, error) {
	fake.saveMutex.Lock()
	ret, specificReturn := fake.saveReturnsOnCall[len(fake.saveArgsForCall)]
	fake.saveArgsForCall = append(fake.saveArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.SaveStub
	fakeReturns := fake.saveReturns
	fake.recordInvocation("Save", []interface{}{arg1, arg2, arg3, arg4})
	fake.saveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStemcellRepo) SaveCallCount() int {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	return len(fake.saveArgsForCall)
}

func (fake *FakeStemcellRepo) SaveCalls(stub func(string, string, string, int) (config.StemcellRecord, error)) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = stub
}

func (fake *FakeStemcellRepo) SaveArgsForCall(i int) (string, string, string, int) {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	argsForCall := fake.saveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeStemcellRepo) SaveReturns(result1 config.StemcellRecord, result2 error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = nil
	fake.saveReturns = struct {
		result1 config.StemcellRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeStemcellRepo) SaveReturnsOnCall(i int, result1 config.StemcellRecord, result2 error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = nil
	if fake.saveReturnsOnCall == nil {
		fake.saveReturnsOnCall = make(map[int]struct {
			result1 config.StemcellRecord
			result2 error
		})
	}
	fake.saveReturnsOnCall[i] = struct {
		result1 config.StemcellRecord
		result2 error
	}{result1, result2}
}

func (fake *FakeStemcellRepo) UpdateCurrent(arg1 string) error {
	fake.updateCurrentMutex.Lock()
	ret, specificReturn := fake.updateCurrentReturnsOnCall[len(fake.updateCurrentArgsForCall)]
	fake.updateCurrentArgsForCall = append(fake.updateCurrentArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.UpdateCurrentStub
	fakeReturns := fake.updateCurrentReturns
	fake.recordInvocation("UpdateCurrent", []interface{}{arg1})
	fake.updateCurrentMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStemcellRepo) UpdateCurrentCallCount() int {
	fake.updateCurrentMutex.RLock()
	defer fake.updateCurrentMutex.RUnlock()
	return len(fake.updateCurrentArgsForCall)
}

func (fake *FakeStemcellRepo) UpdateCurrentCalls(stub func(string) error) {
	fake.updateCurrentMutex.Lock()
	defer fake.updateCurrentMutex.Unlock()
	fake.UpdateCurrentStub = stub
}

func (fake *FakeStemcellRepo) UpdateCurrentArgsForCall(i int) string {
	fake.updateCurrentMutex.RLock()
	defer fake.updateCurrentMutex.RUnlock()
	argsForCall := fake.updateCurrentArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStemcellRepo) UpdateCurrentReturns(result1 error) {
	fake.updateCurrentMutex.Lock()
	defer fake.updateCurrentMutex.Unlock()
	fake.UpdateCurrentStub = nil
	fake.updateCurrentReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStemcellRepo) UpdateCurrentReturnsOnCall(i int, result1 error) {
	fake.updateCurrentMutex.Lock()
	defer fake.updateCurrentMutex.Unlock()
	fake.UpdateCurrentStub = nil
	if fake.updateCurrentReturnsOnCall == nil {
		fake.updateCurrentReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateCurrentReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStemcellRepo) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStemcellRepo) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ config.StemcellRepo = new(FakeStemcellRepo)
