// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-cli/deployment/template"
)

type FakeDeploymentTemplateFactory struct {
	NewDeploymentTemplateFromPathStub        func(path string) (template.DeploymentTemplate, error)
	newDeploymentTemplateFromPathMutex       sync.RWMutex
	newDeploymentTemplateFromPathArgsForCall []struct {
		path string
	}
	newDeploymentTemplateFromPathReturns struct {
		result1 template.DeploymentTemplate
		result2 error
	}
}

func (fake *FakeDeploymentTemplateFactory) NewDeploymentTemplateFromPath(path string) (template.DeploymentTemplate, error) {
	fake.newDeploymentTemplateFromPathMutex.Lock()
	fake.newDeploymentTemplateFromPathArgsForCall = append(fake.newDeploymentTemplateFromPathArgsForCall, struct {
		path string
	}{path})
	fake.newDeploymentTemplateFromPathMutex.Unlock()
	if fake.NewDeploymentTemplateFromPathStub != nil {
		return fake.NewDeploymentTemplateFromPathStub(path)
	} else {
		return fake.newDeploymentTemplateFromPathReturns.result1, fake.newDeploymentTemplateFromPathReturns.result2
	}
}

func (fake *FakeDeploymentTemplateFactory) NewDeploymentTemplateFromPathCallCount() int {
	fake.newDeploymentTemplateFromPathMutex.RLock()
	defer fake.newDeploymentTemplateFromPathMutex.RUnlock()
	return len(fake.newDeploymentTemplateFromPathArgsForCall)
}

func (fake *FakeDeploymentTemplateFactory) NewDeploymentTemplateFromPathArgsForCall(i int) string {
	fake.newDeploymentTemplateFromPathMutex.RLock()
	defer fake.newDeploymentTemplateFromPathMutex.RUnlock()
	return fake.newDeploymentTemplateFromPathArgsForCall[i].path
}

func (fake *FakeDeploymentTemplateFactory) NewDeploymentTemplateFromPathReturns(result1 template.DeploymentTemplate, result2 error) {
	fake.NewDeploymentTemplateFromPathStub = nil
	fake.newDeploymentTemplateFromPathReturns = struct {
		result1 template.DeploymentTemplate
		result2 error
	}{result1, result2}
}

var _ template.DeploymentTemplateFactory = new(FakeDeploymentTemplateFactory)
