// Code generated by counterfeiter. DO NOT EDIT.
package sshfakes

import (
	"context"
	"sync"

	"github.com/cloudfoundry/bosh-cli/v7/director"
	"github.com/cloudfoundry/bosh-cli/v7/ssh"
)

type FakeRunner struct {
	RunStub        func(ssh.ConnectionOpts, director.SSHResult, []string) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 ssh.ConnectionOpts
		arg2 director.SSHResult
		arg3 []string
	}
	runReturns struct {
		result1 error
	}
	runReturnsOnCall map[int]struct {
		result1 error
	}
	RunContextStub        func(context.Context, ssh.ConnectionOpts, director.SSHResult, []string) error
	runContextMutex       sync.RWMutex
	runContextArgsForCall []struct {
		arg1 context.Context
		arg2 ssh.ConnectionOpts
		arg3 director.SSHResult
		arg4 []string
	}
	runContextReturns struct {
		result1 error
	}
	runContextReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRunner) Run(arg1 ssh.ConnectionOpts, arg2 director.SSHResult, arg3 []string) error {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 ssh.ConnectionOpts
		arg2 director.SSHResult
		arg3 []string
	}{arg1, arg2, arg3Copy})
	stub := fake.RunStub
	fakeReturns := fake.runReturns
	fake.recordInvocation("Run", []interface{}{arg1, arg2, arg3Copy})
	fake.runMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRunner) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeRunner) RunCalls(stub func(ssh.ConnectionOpts, director.SSHResult, []string) error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *FakeRunner) RunArgsForCall(i int) (ssh.ConnectionOpts, director.SSHResult, []string) {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRunner) RunReturns(result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRunner) RunReturnsOnCall(i int, result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRunner) RunContext(arg1 context.Context, arg2 ssh.ConnectionOpts, arg3 director.SSHResult, arg4 []string) error {
	var arg4Copy []string
	if arg4 != nil {
		arg4Copy = make([]string, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.runContextMutex.Lock()
	ret, specificReturn := fake.runContextReturnsOnCall[len(fake.runContextArgsForCall)]
	fake.runContextArgsForCall = append(fake.runContextArgsForCall, struct {
		arg1 context.Context
		arg2 ssh.ConnectionOpts
		arg3 director.SSHResult
		arg4 []string
	}{arg1, arg2, arg3, arg4Copy})
	stub := fake.RunContextStub
	fakeReturns := fake.runContextReturns
	fake.recordInvocation("RunContext", []interface{}{arg1, arg2, arg3, arg4Copy})
	fake.runContextMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRunner) RunContextCallCount() int {
	fake.runContextMutex.RLock()
	defer fake.runContextMutex.RUnlock()
	return len(fake.runContextArgsForCall)
}

func (fake *FakeRunner) RunContextCalls(stub func(context.Context, ssh.ConnectionOpts, director.SSHResult, []string) error) {
	fake.runContextMutex.Lock()
	defer fake.runContextMutex.Unlock()
	fake.RunContextStub = stub
}

func (fake *FakeRunner) RunContextArgsForCall(i int) (context.Context, ssh.ConnectionOpts, director.SSHResult, []string) {
	fake.runContextMutex.RLock()
	defer fake.runContextMutex.RUnlock()
	argsForCall := fake.runContextArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeRunner) RunContextReturns(result1 error) {
	fake.runContextMutex.Lock()
	defer fake.runContextMutex.Unlock()
	fake.RunContextStub = nil
	fake.runContextReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRunner) RunContextReturnsOnCall(i int, result1 error) {
	fake.runContextMutex.Lock()
	defer fake.runContextMutex.Unlock()
	fake.RunContextStub = nil
	if fake.runContextReturnsOnCall == nil {
		fake.runContextReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runContextReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ ssh.Runner = new(FakeRunner)
