// This file was generated by counterfeiter
package fakes

import (
	"sync"

	boshdir "github.com/cloudfoundry/bosh-cli/director"
	"github.com/cloudfoundry/bosh-cli/ssh"
)

type FakeRunner struct {
	RunStub        func(ssh.ConnectionOpts, boshdir.SSHResult, []string) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 ssh.ConnectionOpts
		arg2 boshdir.SSHResult
		arg3 []string
	}
	runReturns struct {
		result1 error
	}
}

func (fake *FakeRunner) Run(arg1 ssh.ConnectionOpts, arg2 boshdir.SSHResult, arg3 []string) error {
	fake.runMutex.Lock()
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 ssh.ConnectionOpts
		arg2 boshdir.SSHResult
		arg3 []string
	}{arg1, arg2, arg3})
	fake.runMutex.Unlock()
	if fake.RunStub != nil {
		return fake.RunStub(arg1, arg2, arg3)
	} else {
		return fake.runReturns.result1
	}
}

func (fake *FakeRunner) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeRunner) RunArgsForCall(i int) (ssh.ConnectionOpts, boshdir.SSHResult, []string) {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.runArgsForCall[i].arg1, fake.runArgsForCall[i].arg2, fake.runArgsForCall[i].arg3
}

func (fake *FakeRunner) RunReturns(result1 error) {
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

var _ ssh.Runner = new(FakeRunner)
