// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/cloudfoundry/bosh-micro-cli/deployer/registry (interfaces: Server,ServerFactory)

package mocks

import (
	gomock "code.google.com/p/gomock/gomock"
	registry "github.com/cloudfoundry/bosh-micro-cli/deployer/registry"
)

// Mock of Server interface
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *_MockServerRecorder
}

// Recorder for MockServer (not exported)
type _MockServerRecorder struct {
	mock *MockServer
}

func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &_MockServerRecorder{mock}
	return mock
}

func (_m *MockServer) EXPECT() *_MockServerRecorder {
	return _m.recorder
}

func (_m *MockServer) Stop() error {
	ret := _m.ctrl.Call(_m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockServerRecorder) Stop() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Stop")
}

// Mock of ServerFactory interface
type MockServerFactory struct {
	ctrl     *gomock.Controller
	recorder *_MockServerFactoryRecorder
}

// Recorder for MockServerFactory (not exported)
type _MockServerFactoryRecorder struct {
	mock *MockServerFactory
}

func NewMockServerFactory(ctrl *gomock.Controller) *MockServerFactory {
	mock := &MockServerFactory{ctrl: ctrl}
	mock.recorder = &_MockServerFactoryRecorder{mock}
	return mock
}

func (_m *MockServerFactory) EXPECT() *_MockServerFactoryRecorder {
	return _m.recorder
}

func (_m *MockServerFactory) Create(_param0 string, _param1 string, _param2 string, _param3 int) (registry.Server, error) {
	ret := _m.ctrl.Call(_m, "Create", _param0, _param1, _param2, _param3)
	ret0, _ := ret[0].(registry.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockServerFactoryRecorder) Create(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Create", arg0, arg1, arg2, arg3)
}
