// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-init/release/resource"
)

type FakeArchive struct {
	FingerprintStub        func() (string, error)
	fingerprintMutex       sync.RWMutex
	fingerprintArgsForCall []struct{}
	fingerprintReturns     struct {
		result1 string
		result2 error
	}
	BuildStub        func(expectedFp string) (string, string, error)
	buildMutex       sync.RWMutex
	buildArgsForCall []struct {
		expectedFp string
	}
	buildReturns struct {
		result1 string
		result2 string
		result3 error
	}
}

func (fake *FakeArchive) Fingerprint() (string, error) {
	fake.fingerprintMutex.Lock()
	fake.fingerprintArgsForCall = append(fake.fingerprintArgsForCall, struct{}{})
	fake.fingerprintMutex.Unlock()
	if fake.FingerprintStub != nil {
		return fake.FingerprintStub()
	} else {
		return fake.fingerprintReturns.result1, fake.fingerprintReturns.result2
	}
}

func (fake *FakeArchive) FingerprintCallCount() int {
	fake.fingerprintMutex.RLock()
	defer fake.fingerprintMutex.RUnlock()
	return len(fake.fingerprintArgsForCall)
}

func (fake *FakeArchive) FingerprintReturns(result1 string, result2 error) {
	fake.FingerprintStub = nil
	fake.fingerprintReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeArchive) Build(expectedFp string) (string, string, error) {
	fake.buildMutex.Lock()
	fake.buildArgsForCall = append(fake.buildArgsForCall, struct {
		expectedFp string
	}{expectedFp})
	fake.buildMutex.Unlock()
	if fake.BuildStub != nil {
		return fake.BuildStub(expectedFp)
	} else {
		return fake.buildReturns.result1, fake.buildReturns.result2, fake.buildReturns.result3
	}
}

func (fake *FakeArchive) BuildCallCount() int {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	return len(fake.buildArgsForCall)
}

func (fake *FakeArchive) BuildArgsForCall(i int) string {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	return fake.buildArgsForCall[i].expectedFp
}

func (fake *FakeArchive) BuildReturns(result1 string, result2 string, result3 error) {
	fake.BuildStub = nil
	fake.buildReturns = struct {
		result1 string
		result2 string
		result3 error
	}{result1, result2, result3}
}

var _ resource.Archive = new(FakeArchive)
