jobs:
  - name: build-bosh-cli
    public: true
    serial: true
    plan:
      - in_parallel:
        - get: bosh-cli-src
          trigger: true
        - get: golang-release
          trigger: true
      - task: write-metadata-file
        file: bosh-cli-src/ci/docker/write-metadata-file.yml
        params:
          DOCKER_IMAGE_TAG: latest
      - put: bosh-cli
        params:
          build: "docker-files"
          tag: "docker-files/tag"
        get_params:
          skip_download: true

resources:
  - name: bosh-cli-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-cli.git
      paths:
        - "ci/docker"

  - name: bosh-cli
    type: docker-image
    source:
      repository: bosh/cli
      username: ((docker.username))
      password: ((docker.password))

  - name: golang-release
    type: git
    source:
      uri: https://github.com/bosh-packages/golang-release.git