// Code generated by counterfeiter. DO NOT EDIT.
package jobfakes

import (
	"sync"

	joba "github.com/cloudfoundry/bosh-cli/v7/release/job"
	"github.com/cloudfoundry/bosh-cli/v7/state/job"
	"github.com/cloudfoundry/bosh-cli/v7/ui"
)

type FakeDependencyCompiler struct {
	CompileStub        func([]joba.Job, ui.Stage) ([]job.CompiledPackageRef, error)
	compileMutex       sync.RWMutex
	compileArgsForCall []struct {
		arg1 []joba.Job
		arg2 ui.Stage
	}
	compileReturns struct {
		result1 []job.CompiledPackageRef
		result2 error
	}
	compileReturnsOnCall map[int]struct {
		result1 []job.CompiledPackageRef
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDependencyCompiler) Compile(arg1 []joba.Job, arg2 ui.Stage) ([]job.CompiledPackageRef, error) {
	var arg1Copy []joba.Job
	if arg1 != nil {
		arg1Copy = make([]joba.Job, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.compileMutex.Lock()
	ret, specificReturn := fake.compileReturnsOnCall[len(fake.compileArgsForCall)]
	fake.compileArgsForCall = append(fake.compileArgsForCall, struct {
		arg1 []joba.Job
		arg2 ui.Stage
	}{arg1Copy, arg2})
	stub := fake.CompileStub
	fakeReturns := fake.compileReturns
	fake.recordInvocation("Compile", []interface{}{arg1Copy, arg2})
	fake.compileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDependencyCompiler) CompileCallCount() int {
	fake.compileMutex.RLock()
	defer fake.compileMutex.RUnlock()
	return len(fake.compileArgsForCall)
}

func (fake *FakeDependencyCompiler) CompileCalls(stub func([]joba.Job, ui.Stage) ([]job.CompiledPackageRef, error)) {
	fake.compileMutex.Lock()
	defer fake.compileMutex.Unlock()
	fake.CompileStub = stub
}

func (fake *FakeDependencyCompiler) CompileArgsForCall(i int) ([]joba.Job, ui.Stage) {
	fake.compileMutex.RLock()
	defer fake.compileMutex.RUnlock()
	argsForCall := fake.compileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDependencyCompiler) CompileReturns(result1 []job.CompiledPackageRef, result2 error) {
	fake.compileMutex.Lock()
	defer fake.compileMutex.Unlock()
	fake.CompileStub = nil
	fake.compileReturns = struct {
		result1 []job.CompiledPackageRef
		result2 error
	}{result1, result2}
}

func (fake *FakeDependencyCompiler) CompileReturnsOnCall(i int, result1 []job.CompiledPackageRef, result2 error) {
	fake.compileMutex.Lock()
	defer fake.compileMutex.Unlock()
	fake.CompileStub = nil
	if fake.compileReturnsOnCall == nil {
		fake.compileReturnsOnCall = make(map[int]struct {
			result1 []job.CompiledPackageRef
			result2 error
		})
	}
	fake.compileReturnsOnCall[i] = struct {
		result1 []job.CompiledPackageRef
		result2 error
	}{result1, result2}
}

func (fake *FakeDependencyCompiler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDependencyCompiler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ job.DependencyCompiler = new(FakeDependencyCompiler)
