// Code generated by counterfeiter. DO NOT EDIT.
package deploymentfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-agent/v2/agentclient"
	"github.com/cloudfoundry/bosh-cli/v7/blobstore"
	"github.com/cloudfoundry/bosh-cli/v7/cloud"
	"github.com/cloudfoundry/bosh-cli/v7/deployment"
)

type FakeManagerFactory struct {
	NewManagerStub        func(cloud.Cloud, agentclient.AgentClient, blobstore.Blobstore) deployment.Manager
	newManagerMutex       sync.RWMutex
	newManagerArgsForCall []struct {
		arg1 cloud.Cloud
		arg2 agentclient.AgentClient
		arg3 blobstore.Blobstore
	}
	newManagerReturns struct {
		result1 deployment.Manager
	}
	newManagerReturnsOnCall map[int]struct {
		result1 deployment.Manager
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeManagerFactory) NewManager(arg1 cloud.Cloud, arg2 agentclient.AgentClient, arg3 blobstore.Blobstore) deployment.Manager {
	fake.newManagerMutex.Lock()
	ret, specificReturn := fake.newManagerReturnsOnCall[len(fake.newManagerArgsForCall)]
	fake.newManagerArgsForCall = append(fake.newManagerArgsForCall, struct {
		arg1 cloud.Cloud
		arg2 agentclient.AgentClient
		arg3 blobstore.Blobstore
	}{arg1, arg2, arg3})
	stub := fake.NewManagerStub
	fakeReturns := fake.newManagerReturns
	fake.recordInvocation("NewManager", []interface{}{arg1, arg2, arg3})
	fake.newManagerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeManagerFactory) NewManagerCallCount() int {
	fake.newManagerMutex.RLock()
	defer fake.newManagerMutex.RUnlock()
	return len(fake.newManagerArgsForCall)
}

func (fake *FakeManagerFactory) NewManagerCalls(stub func(cloud.Cloud, agentclient.AgentClient, blobstore.Blobstore) deployment.Manager) {
	fake.newManagerMutex.Lock()
	defer fake.newManagerMutex.Unlock()
	fake.NewManagerStub = stub
}

func (fake *FakeManagerFactory) NewManagerArgsForCall(i int) (cloud.Cloud, agentclient.AgentClient, blobstore.Blobstore) {
	fake.newManagerMutex.RLock()
	defer fake.newManagerMutex.RUnlock()
	argsForCall := fake.newManagerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeManagerFactory) NewManagerReturns(result1 deployment.Manager) {
	fake.newManagerMutex.Lock()
	defer fake.newManagerMutex.Unlock()
	fake.NewManagerStub = nil
	fake.newManagerReturns = struct {
		result1 deployment.Manager
	}{result1}
}

func (fake *FakeManagerFactory) NewManagerReturnsOnCall(i int, result1 deployment.Manager) {
	fake.newManagerMutex.Lock()
	defer fake.newManagerMutex.Unlock()
	fake.NewManagerStub = nil
	if fake.newManagerReturnsOnCall == nil {
		fake.newManagerReturnsOnCall = make(map[int]struct {
			result1 deployment.Manager
		})
	}
	fake.newManagerReturnsOnCall[i] = struct {
		result1 deployment.Manager
	}{result1}
}

func (fake *FakeManagerFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeManagerFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ deployment.ManagerFactory = new(FakeManagerFactory)
