// Code generated by counterfeiter. DO NOT EDIT.
package mockfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-cli/v7/stemcell"
	"github.com/cloudfoundry/bosh-cli/v7/ui"
)

type FakeManager struct {
	DeleteUnusedStub        func(ui.Stage) error
	deleteUnusedMutex       sync.RWMutex
	deleteUnusedArgsForCall []struct {
		arg1 ui.Stage
	}
	deleteUnusedReturns struct {
		result1 error
	}
	deleteUnusedReturnsOnCall map[int]struct {
		result1 error
	}
	FindCurrentStub        func() ([]stemcell.CloudStemcell, error)
	findCurrentMutex       sync.RWMutex
	findCurrentArgsForCall []struct {
	}
	findCurrentReturns struct {
		result1 []stemcell.CloudStemcell
		result2 error
	}
	findCurrentReturnsOnCall map[int]struct {
		result1 []stemcell.CloudStemcell
		result2 error
	}
	FindUnusedStub        func() ([]stemcell.CloudStemcell, error)
	findUnusedMutex       sync.RWMutex
	findUnusedArgsForCall []struct {
	}
	findUnusedReturns struct {
		result1 []stemcell.CloudStemcell
		result2 error
	}
	findUnusedReturnsOnCall map[int]struct {
		result1 []stemcell.CloudStemcell
		result2 error
	}
	UploadStub        func(stemcell.ExtractedStemcell, ui.Stage) (stemcell.CloudStemcell, error)
	uploadMutex       sync.RWMutex
	uploadArgsForCall []struct {
		arg1 stemcell.ExtractedStemcell
		arg2 ui.Stage
	}
	uploadReturns struct {
		result1 stemcell.CloudStemcell
		result2 error
	}
	uploadReturnsOnCall map[int]struct {
		result1 stemcell.CloudStemcell
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeManager) DeleteUnused(arg1 ui.Stage) error {
	fake.deleteUnusedMutex.Lock()
	ret, specificReturn := fake.deleteUnusedReturnsOnCall[len(fake.deleteUnusedArgsForCall)]
	fake.deleteUnusedArgsForCall = append(fake.deleteUnusedArgsForCall, struct {
		arg1 ui.Stage
	}{arg1})
	stub := fake.DeleteUnusedStub
	fakeReturns := fake.deleteUnusedReturns
	fake.recordInvocation("DeleteUnused", []interface{}{arg1})
	fake.deleteUnusedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeManager) DeleteUnusedCallCount() int {
	fake.deleteUnusedMutex.RLock()
	defer fake.deleteUnusedMutex.RUnlock()
	return len(fake.deleteUnusedArgsForCall)
}

func (fake *FakeManager) DeleteUnusedCalls(stub func(ui.Stage) error) {
	fake.deleteUnusedMutex.Lock()
	defer fake.deleteUnusedMutex.Unlock()
	fake.DeleteUnusedStub = stub
}

func (fake *FakeManager) DeleteUnusedArgsForCall(i int) ui.Stage {
	fake.deleteUnusedMutex.RLock()
	defer fake.deleteUnusedMutex.RUnlock()
	argsForCall := fake.deleteUnusedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeManager) DeleteUnusedReturns(result1 error) {
	fake.deleteUnusedMutex.Lock()
	defer fake.deleteUnusedMutex.Unlock()
	fake.DeleteUnusedStub = nil
	fake.deleteUnusedReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeManager) DeleteUnusedReturnsOnCall(i int, result1 error) {
	fake.deleteUnusedMutex.Lock()
	defer fake.deleteUnusedMutex.Unlock()
	fake.DeleteUnusedStub = nil
	if fake.deleteUnusedReturnsOnCall == nil {
		fake.deleteUnusedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteUnusedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeManager) FindCurrent() ([]stemcell.CloudStemcell, error) {
	fake.findCurrentMutex.Lock()
	ret, specificReturn := fake.findCurrentReturnsOnCall[len(fake.findCurrentArgsForCall)]
	fake.findCurrentArgsForCall = append(fake.findCurrentArgsForCall, struct {
	}{})
	stub := fake.FindCurrentStub
	fakeReturns := fake.findCurrentReturns
	fake.recordInvocation("FindCurrent", []interface{}{})
	fake.findCurrentMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeManager) FindCurrentCallCount() int {
	fake.findCurrentMutex.RLock()
	defer fake.findCurrentMutex.RUnlock()
	return len(fake.findCurrentArgsForCall)
}

func (fake *FakeManager) FindCurrentCalls(stub func() ([]stemcell.CloudStemcell, error)) {
	fake.findCurrentMutex.Lock()
	defer fake.findCurrentMutex.Unlock()
	fake.FindCurrentStub = stub
}

func (fake *FakeManager) FindCurrentReturns(result1 []stemcell.CloudStemcell, result2 error) {
	fake.findCurrentMutex.Lock()
	defer fake.findCurrentMutex.Unlock()
	fake.FindCurrentStub = nil
	fake.findCurrentReturns = struct {
		result1 []stemcell.CloudStemcell
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) FindCurrentReturnsOnCall(i int, result1 []stemcell.CloudStemcell, result2 error) {
	fake.findCurrentMutex.Lock()
	defer fake.findCurrentMutex.Unlock()
	fake.FindCurrentStub = nil
	if fake.findCurrentReturnsOnCall == nil {
		fake.findCurrentReturnsOnCall = make(map[int]struct {
			result1 []stemcell.CloudStemcell
			result2 error
		})
	}
	fake.findCurrentReturnsOnCall[i] = struct {
		result1 []stemcell.CloudStemcell
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) FindUnused() ([]stemcell.CloudStemcell, error) {
	fake.findUnusedMutex.Lock()
	ret, specificReturn := fake.findUnusedReturnsOnCall[len(fake.findUnusedArgsForCall)]
	fake.findUnusedArgsForCall = append(fake.findUnusedArgsForCall, struct {
	}{})
	stub := fake.FindUnusedStub
	fakeReturns := fake.findUnusedReturns
	fake.recordInvocation("FindUnused", []interface{}{})
	fake.findUnusedMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeManager) FindUnusedCallCount() int {
	fake.findUnusedMutex.RLock()
	defer fake.findUnusedMutex.RUnlock()
	return len(fake.findUnusedArgsForCall)
}

func (fake *FakeManager) FindUnusedCalls(stub func() ([]stemcell.CloudStemcell, error)) {
	fake.findUnusedMutex.Lock()
	defer fake.findUnusedMutex.Unlock()
	fake.FindUnusedStub = stub
}

func (fake *FakeManager) FindUnusedReturns(result1 []stemcell.CloudStemcell, result2 error) {
	fake.findUnusedMutex.Lock()
	defer fake.findUnusedMutex.Unlock()
	fake.FindUnusedStub = nil
	fake.findUnusedReturns = struct {
		result1 []stemcell.CloudStemcell
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) FindUnusedReturnsOnCall(i int, result1 []stemcell.CloudStemcell, result2 error) {
	fake.findUnusedMutex.Lock()
	defer fake.findUnusedMutex.Unlock()
	fake.FindUnusedStub = nil
	if fake.findUnusedReturnsOnCall == nil {
		fake.findUnusedReturnsOnCall = make(map[int]struct {
			result1 []stemcell.CloudStemcell
			result2 error
		})
	}
	fake.findUnusedReturnsOnCall[i] = struct {
		result1 []stemcell.CloudStemcell
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) Upload(arg1 stemcell.ExtractedStemcell, arg2 ui.Stage) (stemcell.CloudStemcell, error) {
	fake.uploadMutex.Lock()
	ret, specificReturn := fake.uploadReturnsOnCall[len(fake.uploadArgsForCall)]
	fake.uploadArgsForCall = append(fake.uploadArgsForCall, struct {
		arg1 stemcell.ExtractedStemcell
		arg2 ui.Stage
	}{arg1, arg2})
	stub := fake.UploadStub
	fakeReturns := fake.uploadReturns
	fake.recordInvocation("Upload", []interface{}{arg1, arg2})
	fake.uploadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeManager) UploadCallCount() int {
	fake.uploadMutex.RLock()
	defer fake.uploadMutex.RUnlock()
	return len(fake.uploadArgsForCall)
}

func (fake *FakeManager) UploadCalls(stub func(stemcell.ExtractedStemcell, ui.Stage) (stemcell.CloudStemcell, error)) {
	fake.uploadMutex.Lock()
	defer fake.uploadMutex.Unlock()
	fake.UploadStub = stub
}

func (fake *FakeManager) UploadArgsForCall(i int) (stemcell.ExtractedStemcell, ui.Stage) {
	fake.uploadMutex.RLock()
	defer fake.uploadMutex.RUnlock()
	argsForCall := fake.uploadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeManager) UploadReturns(result1 stemcell.CloudStemcell, result2 error) {
	fake.uploadMutex.Lock()
	defer fake.uploadMutex.Unlock()
	fake.UploadStub = nil
	fake.uploadReturns = struct {
		result1 stemcell.CloudStemcell
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) UploadReturnsOnCall(i int, result1 stemcell.CloudStemcell, result2 error) {
	fake.uploadMutex.Lock()
	defer fake.uploadMutex.Unlock()
	fake.UploadStub = nil
	if fake.uploadReturnsOnCall == nil {
		fake.uploadReturnsOnCall = make(map[int]struct {
			result1 stemcell.CloudStemcell
			result2 error
		})
	}
	fake.uploadReturnsOnCall[i] = struct {
		result1 stemcell.CloudStemcell
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ stemcell.Manager = new(FakeManager)
