// This file was generated by counterfeiter
package manifestfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-cli/director/template"
	"github.com/cloudfoundry/bosh-cli/release/set/manifest"
	"github.com/cppforlife/go-patch/patch"
)

type FakeParser struct {
	ParseStub        func(string, template.Variables, patch.Ops) (manifest.Manifest, error)
	parseMutex       sync.RWMutex
	parseArgsForCall []struct {
		arg1 string
		arg2 template.Variables
		arg3 patch.Ops
	}
	parseReturns struct {
		result1 manifest.Manifest
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeParser) Parse(arg1 string, arg2 template.Variables, arg3 patch.Ops) (manifest.Manifest, error) {
	fake.parseMutex.Lock()
	fake.parseArgsForCall = append(fake.parseArgsForCall, struct {
		arg1 string
		arg2 template.Variables
		arg3 patch.Ops
	}{arg1, arg2, arg3})
	fake.recordInvocation("Parse", []interface{}{arg1, arg2, arg3})
	fake.parseMutex.Unlock()
	if fake.ParseStub != nil {
		return fake.ParseStub(arg1, arg2, arg3)
	} else {
		return fake.parseReturns.result1, fake.parseReturns.result2
	}
}

func (fake *FakeParser) ParseCallCount() int {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	return len(fake.parseArgsForCall)
}

func (fake *FakeParser) ParseArgsForCall(i int) (string, template.Variables, patch.Ops) {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	return fake.parseArgsForCall[i].arg1, fake.parseArgsForCall[i].arg2, fake.parseArgsForCall[i].arg3
}

func (fake *FakeParser) ParseReturns(result1 manifest.Manifest, result2 error) {
	fake.ParseStub = nil
	fake.parseReturns = struct {
		result1 manifest.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakeParser) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeParser) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ manifest.Parser = new(FakeParser)
