// Code generated by counterfeiter. DO NOT EDIT.
package pkgfakes

import (
	"sync"

	pkga "github.com/cloudfoundry/bosh-cli/v7/release/pkg"
	"github.com/cloudfoundry/bosh-cli/v7/state/pkg"
)

type FakeCompiledPackageRepo struct {
	FindStub        func(pkga.Compilable) (pkg.CompiledPackageRecord, bool, error)
	findMutex       sync.RWMutex
	findArgsForCall []struct {
		arg1 pkga.Compilable
	}
	findReturns struct {
		result1 pkg.CompiledPackageRecord
		result2 bool
		result3 error
	}
	findReturnsOnCall map[int]struct {
		result1 pkg.CompiledPackageRecord
		result2 bool
		result3 error
	}
	SaveStub        func(pkga.Compilable, pkg.CompiledPackageRecord) error
	saveMutex       sync.RWMutex
	saveArgsForCall []struct {
		arg1 pkga.Compilable
		arg2 pkg.CompiledPackageRecord
	}
	saveReturns struct {
		result1 error
	}
	saveReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCompiledPackageRepo) Find(arg1 pkga.Compilable) (pkg.CompiledPackageRecord, bool, error) {
	fake.findMutex.Lock()
	ret, specificReturn := fake.findReturnsOnCall[len(fake.findArgsForCall)]
	fake.findArgsForCall = append(fake.findArgsForCall, struct {
		arg1 pkga.Compilable
	}{arg1})
	stub := fake.FindStub
	fakeReturns := fake.findReturns
	fake.recordInvocation("Find", []interface{}{arg1})
	fake.findMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeCompiledPackageRepo) FindCallCount() int {
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	return len(fake.findArgsForCall)
}

func (fake *FakeCompiledPackageRepo) FindCalls(stub func(pkga.Compilable) (pkg.CompiledPackageRecord, bool, error)) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = stub
}

func (fake *FakeCompiledPackageRepo) FindArgsForCall(i int) pkga.Compilable {
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	argsForCall := fake.findArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCompiledPackageRepo) FindReturns(result1 pkg.CompiledPackageRecord, result2 bool, result3 error) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = nil
	fake.findReturns = struct {
		result1 pkg.CompiledPackageRecord
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCompiledPackageRepo) FindReturnsOnCall(i int, result1 pkg.CompiledPackageRecord, result2 bool, result3 error) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = nil
	if fake.findReturnsOnCall == nil {
		fake.findReturnsOnCall = make(map[int]struct {
			result1 pkg.CompiledPackageRecord
			result2 bool
			result3 error
		})
	}
	fake.findReturnsOnCall[i] = struct {
		result1 pkg.CompiledPackageRecord
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCompiledPackageRepo) Save(arg1 pkga.Compilable, arg2 pkg.CompiledPackageRecord) error {
	fake.saveMutex.Lock()
	ret, specificReturn := fake.saveReturnsOnCall[len(fake.saveArgsForCall)]
	fake.saveArgsForCall = append(fake.saveArgsForCall, struct {
		arg1 pkga.Compilable
		arg2 pkg.CompiledPackageRecord
	}{arg1, arg2})
	stub := fake.SaveStub
	fakeReturns := fake.saveReturns
	fake.recordInvocation("Save", []interface{}{arg1, arg2})
	fake.saveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCompiledPackageRepo) SaveCallCount() int {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	return len(fake.saveArgsForCall)
}

func (fake *FakeCompiledPackageRepo) SaveCalls(stub func(pkga.Compilable, pkg.CompiledPackageRecord) error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = stub
}

func (fake *FakeCompiledPackageRepo) SaveArgsForCall(i int) (pkga.Compilable, pkg.CompiledPackageRecord) {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	argsForCall := fake.saveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCompiledPackageRepo) SaveReturns(result1 error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = nil
	fake.saveReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCompiledPackageRepo) SaveReturnsOnCall(i int, result1 error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = nil
	if fake.saveReturnsOnCall == nil {
		fake.saveReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCompiledPackageRepo) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCompiledPackageRepo) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.CompiledPackageRepo = new(FakeCompiledPackageRepo)
