// Code generated by counterfeiter. DO NOT EDIT.
package pkgfakes

import (
	"sync"

	pkga "github.com/cloudfoundry/bosh-cli/v7/release/pkg"
	"github.com/cloudfoundry/bosh-cli/v7/state/pkg"
)

type FakeCompiler struct {
	CompileStub        func(pkga.Compilable) (pkg.CompiledPackageRecord, bool, error)
	compileMutex       sync.RWMutex
	compileArgsForCall []struct {
		arg1 pkga.Compilable
	}
	compileReturns struct {
		result1 pkg.CompiledPackageRecord
		result2 bool
		result3 error
	}
	compileReturnsOnCall map[int]struct {
		result1 pkg.CompiledPackageRecord
		result2 bool
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCompiler) Compile(arg1 pkga.Compilable) (pkg.CompiledPackageRecord, bool, error) {
	fake.compileMutex.Lock()
	ret, specificReturn := fake.compileReturnsOnCall[len(fake.compileArgsForCall)]
	fake.compileArgsForCall = append(fake.compileArgsForCall, struct {
		arg1 pkga.Compilable
	}{arg1})
	stub := fake.CompileStub
	fakeReturns := fake.compileReturns
	fake.recordInvocation("Compile", []interface{}{arg1})
	fake.compileMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeCompiler) CompileCallCount() int {
	fake.compileMutex.RLock()
	defer fake.compileMutex.RUnlock()
	return len(fake.compileArgsForCall)
}

func (fake *FakeCompiler) CompileCalls(stub func(pkga.Compilable) (pkg.CompiledPackageRecord, bool, error)) {
	fake.compileMutex.Lock()
	defer fake.compileMutex.Unlock()
	fake.CompileStub = stub
}

func (fake *FakeCompiler) CompileArgsForCall(i int) pkga.Compilable {
	fake.compileMutex.RLock()
	defer fake.compileMutex.RUnlock()
	argsForCall := fake.compileArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCompiler) CompileReturns(result1 pkg.CompiledPackageRecord, result2 bool, result3 error) {
	fake.compileMutex.Lock()
	defer fake.compileMutex.Unlock()
	fake.CompileStub = nil
	fake.compileReturns = struct {
		result1 pkg.CompiledPackageRecord
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCompiler) CompileReturnsOnCall(i int, result1 pkg.CompiledPackageRecord, result2 bool, result3 error) {
	fake.compileMutex.Lock()
	defer fake.compileMutex.Unlock()
	fake.CompileStub = nil
	if fake.compileReturnsOnCall == nil {
		fake.compileReturnsOnCall = make(map[int]struct {
			result1 pkg.CompiledPackageRecord
			result2 bool
			result3 error
		})
	}
	fake.compileReturnsOnCall[i] = struct {
		result1 pkg.CompiledPackageRecord
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCompiler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCompiler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.Compiler = new(FakeCompiler)
