---
jobs:
  - name: bump-deps
    public: true
    plan:
      - get: weekly
        trigger: true
      - get: bosh-cli
      - get: golang-release
      - task: bump-deps
        file: golang-release/ci/tasks/shared/bump-deps.yml
        input_mapping:
          input_repo: bosh-cli
        output_mapping:
          output_repo: bumped-bosh-cli
      - task: test-unit
        input_mapping:
          bosh-cli: bumped-bosh-cli
        file: bosh-cli/ci/tasks/test-unit.yml
      - put: bosh-cli
        params:
          repository: bumped-bosh-cli

  - name: test-unit
    public: true
    plan:
      - get: bosh-cli
        trigger: true
      - task: test-unit
        file: bosh-cli/ci/tasks/test-unit.yml

  - name: test-integration
    public: true
    plan:
      - get: bosh-cli
        trigger: true
      - task: test-integration
        file: bosh-cli/ci/tasks/test-integration.yml
        privileged: true

  - name: test-acceptance-xenial
    public: true
    plan:
      - in_parallel:
        - get: bosh-cli
          passed: [test-unit,test-integration]
          trigger: true
        - get: bosh-warden-cpi-release
          trigger: true
        - get: bosh-warden-stemcell-xenial
      - in_parallel:
        - task: test-acceptance
          file: bosh-cli/ci/tasks/test-acceptance.yml
          privileged: true

  - name: integration-postgres
    public: true
    serial: true
    build_logs_to_retain: 250
    plan:
      - in_parallel:
        - get: bosh-src
          trigger: true
        - get: version-semver
          params: {bump: patch}
        - get: bosh-cli
          passed: [test-unit,test-integration]
          trigger: true
        - get: bosh-agent
          trigger: true
        - get: integration-tests-parallel-runtime

      - task: build-linux-amd64
        file: bosh-cli/ci/tasks/build-linux-amd64.yml

      - task: tests
        privileged: true
        input_mapping:
          bosh-cli: compiled-linux-amd64
        file: bosh-src/ci/tasks/test-integration.yml
        params:
          DB: postgresql
          DB_VERSION: 13

  - name: pre-release-fan-in
    public: true
    serial: true
    plan:
      - get: bosh-cli
        trigger: true
        passed:
        - test-acceptance-xenial
        - integration-postgres

  - name: release-new-patch
    public: true
    plan:
      - get: bosh-cli
        passed:
        - pre-release-fan-in
      - put: version-semver
        params:
          bump: patch

  - name: release-new-minor
    public: true
    plan:
      - get: bosh-cli
        passed:
        - pre-release-fan-in
      - put: version-semver
        params:
          bump: minor

  - name: release-new-major
    public: true
    plan:
      - get: bosh-cli
        passed:
        - pre-release-fan-in
      - put: version-semver
        params:
          bump: major

  - name: automatically-release-new-patch
    serial: true
    plan:
    - in_parallel:
      - get: bosh-cli
        trigger: true
        passed:
        - pre-release-fan-in
      - get: golang-release
      - get: version-semver
      - get: ubuntu-image
    - try:
        task: check-for-patched-cves
        file: golang-release/ci/tasks/shared/check-for-patched-cves.yml
        input_mapping:
          input_repo: bosh-cli
          version: version-semver
        params:
          SEVERITY: CRITICAL,HIGH
          SOURCE_PATH: # root path
        on_success:
          do:
          - put: release-notes
            params:
              file: patched_cves/release-notes.md
          - put: version-semver
            params:
              bump: patch
    - task: ensure-cve-checker-succeeded
      file: golang-release/ci/tasks/shared/ensure-cve-checker-succeeded.yml
      image: ubuntu-image
      params:
        description: |
          Since the previous step is wrapped in a "try", this task checks that the previous step fully executed.

  - name: build
    public: true
    plan:
      - in_parallel:
        - get: bosh-cli
          passed:
           - pre-release-fan-in
        - get: version-semver
          trigger: true
        - get: release-notes
        - get: homebrew-tap
      - in_parallel:
        - task: build-linux-amd64
          file: bosh-cli/ci/tasks/build-linux-amd64.yml
        - task: build-darwin-amd64
          file: bosh-cli/ci/tasks/build-darwin-amd64.yml
        - task: build-darwin-arm64
          file: bosh-cli/ci/tasks/build-darwin-arm64.yml
        - task: build-windows-amd64
          file: bosh-cli/ci/tasks/build-windows-amd64.yml

      - task: build-checksum-file
        file: bosh-cli/ci/tasks/build-checksum-file.yml

      - task: create-dockerfile
        file: bosh-cli/ci/tasks/create-dockerfile.yml

      - put: bosh-cli-commit-status
        params:
          state: success
          commit: bosh-cli

      - {put: bosh-cli, params: {repository: bosh-cli, tag: version-semver/number, tag_prefix: v}}

      - in_parallel:
        - {put: release-bucket-linux, params: {file: compiled-linux-amd64/bosh-cli-*-linux-amd64}}
        - {put: release-bucket-darwin, params: {file: compiled-darwin-amd64/bosh-cli-*-darwin-amd64}}
        - {put: release-bucket-darwin-arm64, params: {file: compiled-darwin-arm64/bosh-cli-*-darwin-arm64}}
        - {put: release-bucket-windows, params: {file: compiled-windows-amd64/bosh-cli-*-windows-amd64.exe}}

        - put: final-docker
          params:
            build: docker-assets
            tag: version-semver/number
            tag_as_latest: true

      - do:
        - task: prepare-version
          config:
            platform: linux
            image_resource:
              type: docker-image
              source: {repository: alpine}
            run:
              path: /bin/sh
              args:
              - -c
              - |
                echo -n "v" >> release-version/version
                cat version-semver/number >> release-version/version
            inputs:
            - name: version-semver
            outputs:
            - name: release-version
        - put: github-release
          params:
            name: release-version/version
            tag: release-version/version
            globs:
              - compiled-linux-amd64/bosh-cli-*-linux-amd64
              - compiled-darwin-amd64/bosh-cli-*-darwin-amd64
              - compiled-darwin-arm64/bosh-cli-*-darwin-arm64
              - compiled-windows-amd64/bosh-cli-*-windows-amd64.exe
            body: checksums/checksums

      - task: update-homebrew-formula
        file: bosh-cli/ci/tasks/update-homebrew-formula.yml
      - put: homebrew-tap
        params:
          repository: update-brew-formula-output/homebrew-tap

  - name: clear-release-notes
    plan:
    - get: version-semver
      passed:
      - build
      trigger: true
    - get: golang-release
    - task: clear-release-notes
      file: golang-release/ci/tasks/shared/clear-release-notes.yml
    - put: release-notes
      params:
        file: release-notes/release-notes.md

  - name: build-alpha
    public: true
    plan:
      - in_parallel:
        - get: bosh-cli
          passed:
           - pre-release-fan-in
          trigger: true
        - get: alpha-version-semver
          params: {bump: patch}
      - {put: alpha-version-semver, params: {file: alpha-version-semver/number}}
      - in_parallel:
        - task: build-linux-amd64
          input_mapping: {version-semver: alpha-version-semver}
          file: bosh-cli/ci/tasks/build-linux-amd64.yml
          params:
            FILENAME_PREFIX: "alpha-"
        - task: build-darwin-amd64
          input_mapping: {version-semver: alpha-version-semver}
          file: bosh-cli/ci/tasks/build-darwin-amd64.yml
          params:
            FILENAME_PREFIX: "alpha-"
        - task: build-darwin-arm64
          input_mapping: {version-semver: alpha-version-semver}
          file: bosh-cli/ci/tasks/build-darwin-arm64.yml
          params:
            FILENAME_PREFIX: "alpha-"
        - task: build-windows-amd64
          input_mapping: {version-semver: alpha-version-semver}
          file: bosh-cli/ci/tasks/build-windows-amd64.yml
          params:
            FILENAME_PREFIX: "alpha-"

      - in_parallel:
        - {put: alpha-release-bucket-linux-amd64, params: {file: compiled-linux-amd64/alpha-bosh-cli-*-linux-amd64}}
        - {put: alpha-release-bucket-darwin-amd64, params: {file: compiled-darwin-amd64/alpha-bosh-cli-*-darwin-amd64}}
        - {put: alpha-release-bucket-darwin-arm64, params: {file: compiled-darwin-arm64/alpha-bosh-cli-*-darwin-arm64}}
        - {put: alpha-release-bucket-windows-amd64, params: {file: compiled-windows-amd64/alpha-bosh-cli-*-windows-amd64.exe}}

  - name: test-helper-urls
    public: true
    plan:
      - in_parallel:
        - get: alpha-release-bucket-linux-amd64
          passed: [build-alpha]
        - get: bosh-cli
          passed: [build-alpha]
      - task: test-helper-urls
        file: bosh-cli/ci/tasks/test-helper-urls.yml

resources:
  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git

  - name: bosh-agent
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-agent.git
      branch: main

  - name: bosh-cli
    type: git
    source:
      uri: git@github.com:cloudfoundry/bosh-cli.git
      branch: main
      private_key: ((github_deploy_key_bosh-cli.private_key))

  - name: bosh-warden-stemcell-xenial
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-xenial-go_agent

  - name: bosh-warden-cpi-release
    type: bosh-io-release
    source:
      repository: cppforlife/bosh-warden-cpi-release

  - name: bosh-cli-commit-status
    type: github-status
    source:
      repository: cloudfoundry/bosh-cli
      access_token: ((github_read_write_token))
      branch: main
      context: ci/published

  - name: golang-release
    type: git
    source:
      uri: https://github.com/bosh-packages/golang-release.git

  - name: release-bucket-linux
    type: s3
    source:
      regexp: bosh-cli-(.*)-linux-amd64
      bucket: bosh-cli-artifacts
      region_name: us-east-1
      access_key_id: ((bosh-cli-artifacts-upload_aws_access_key.username))
      secret_access_key: ((bosh-cli-artifacts-upload_aws_access_key.password))

  - name: release-bucket-darwin
    type: s3
    source:
      regexp: bosh-cli-(.*)-darwin-amd64
      bucket: bosh-cli-artifacts
      region_name: us-east-1
      access_key_id: ((bosh-cli-artifacts-upload_aws_access_key.username))
      secret_access_key: ((bosh-cli-artifacts-upload_aws_access_key.password))

  - name: release-bucket-darwin-arm64
    type: s3
    source:
      regexp: bosh-cli-(.*)-darwin-arm64
      bucket: bosh-cli-artifacts
      region_name: us-east-1
      access_key_id: ((bosh-cli-artifacts-upload_aws_access_key.username))
      secret_access_key: ((bosh-cli-artifacts-upload_aws_access_key.password))

  - name: release-bucket-windows
    type: s3
    source:
      regexp: bosh-cli-(.*)-windows-amd64.exe
      bucket: bosh-cli-artifacts
      region_name: us-east-1
      access_key_id: ((bosh-cli-artifacts-upload_aws_access_key.username))
      secret_access_key: ((bosh-cli-artifacts-upload_aws_access_key.password))

  - name: alpha-release-bucket-linux-amd64
    type: s3
    source:
      regexp: alpha-bosh-cli-(.*)-linux-amd64
      bucket: bosh-cli-alpha-artifacts
      region_name: us-east-1
      access_key_id: ((bosh-cli-artifacts-upload_aws_access_key.username))
      secret_access_key: ((bosh-cli-artifacts-upload_aws_access_key.password))

  - name: alpha-release-bucket-darwin-amd64
    type: s3
    source:
      regexp: alpha-bosh-cli-(.*)-darwin-amd64
      bucket: bosh-cli-alpha-artifacts
      region_name: us-east-1
      access_key_id: ((bosh-cli-artifacts-upload_aws_access_key.username))
      secret_access_key: ((bosh-cli-artifacts-upload_aws_access_key.password))

  - name: alpha-release-bucket-darwin-arm64
    type: s3
    source:
      regexp: alpha-bosh-cli-(.*)-darwin-arm64
      bucket: bosh-cli-alpha-artifacts
      region_name: us-east-1
      access_key_id: ((bosh-cli-artifacts-upload_aws_access_key.username))
      secret_access_key: ((bosh-cli-artifacts-upload_aws_access_key.password))

  - name: alpha-release-bucket-windows-amd64
    type: s3
    source:
      regexp: alpha-bosh-cli-(.*)-windows-amd64.exe
      bucket: bosh-cli-alpha-artifacts
      region_name: us-east-1
      access_key_id: ((bosh-cli-artifacts-upload_aws_access_key.username))
      secret_access_key: ((bosh-cli-artifacts-upload_aws_access_key.password))

  - name: version-semver
    type: semver
    source:
      initial_version: 0.0.1
      key: cli-current-version
      bucket: bosh-cli-artifacts
      access_key_id: ((bosh-cli-artifacts-upload_aws_access_key.username))
      secret_access_key: ((bosh-cli-artifacts-upload_aws_access_key.password))

  - name: alpha-version-semver
    type: semver
    source:
      initial_version: 0.0.1
      key: cli-alpha-current-version
      bucket: bosh-cli-alpha-artifacts
      access_key_id: ((bosh-cli-artifacts-upload_aws_access_key.username))
      secret_access_key: ((bosh-cli-artifacts-upload_aws_access_key.password))

  - name: homebrew-tap
    type: git
    source:
      uri: git@github.com:cloudfoundry/homebrew-tap
      branch: master
      private_key: ((github_deploy_key_homebrew-tap.private_key))

  - name: github-release
    type: github-release
    source:
      owner: cloudfoundry
      repository: bosh-cli
      access_token: ((github_read_write_token))

  - name: final-docker
    type: docker-image
    source:
      repository: bosh/cli2
      username: ((docker.username))
      password: ((docker.password))
      email: foo@bar.com

  - name: ubuntu-image
    type: docker-image
    source:
      repository: ubuntu
      username: ((docker.username))
      password: ((docker.password))
      email: foo@bar.com

  - name: weekly
    type: time
    source:
      start: 3:00 -0700
      stop: 4:30 -0700
      days: [Saturday]

  - name: integration-tests-parallel-runtime
    type: s3
    source:
      bucket: integration-tests-parallel-runtime-logs
      access_key_id: ((bosh_integration_tests_parallel_aws_access_key.username))
      secret_access_key: ((bosh_integration_tests_parallel_aws_access_key.password))
      versioned_file: "parallel_runtime_rspec.log"

  - name: release-notes
    type: gcs-resource
    source:
      bucket: bosh-ci-release-notes
      json_key: ((gcp_credentials_json))
      versioned_file: bosh-cli/release-notes.md
      initial_version: "0"
      initial_content_text: ""

resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource
      username: ((docker.username))
      password: ((docker.password))
  - name: github-status
    type: docker-image
    source:
      repository: dpb587/github-status-resource
      tag: master
