// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/cloudfoundry/bosh-micro-cli/installation/pkg (interfaces: PackageCompiler,PackageInstaller)

package mocks

import (
	gomock "code.google.com/p/gomock/gomock"
	pkg0 "github.com/cloudfoundry/bosh-micro-cli/installation/pkg"
	pkg "github.com/cloudfoundry/bosh-micro-cli/release/pkg"
)

// Mock of PackageCompiler interface
type MockPackageCompiler struct {
	ctrl     *gomock.Controller
	recorder *_MockPackageCompilerRecorder
}

// Recorder for MockPackageCompiler (not exported)
type _MockPackageCompilerRecorder struct {
	mock *MockPackageCompiler
}

func NewMockPackageCompiler(ctrl *gomock.Controller) *MockPackageCompiler {
	mock := &MockPackageCompiler{ctrl: ctrl}
	mock.recorder = &_MockPackageCompilerRecorder{mock}
	return mock
}

func (_m *MockPackageCompiler) EXPECT() *_MockPackageCompilerRecorder {
	return _m.recorder
}

func (_m *MockPackageCompiler) Compile(_param0 *pkg.Package) (pkg0.CompiledPackageRecord, error) {
	ret := _m.ctrl.Call(_m, "Compile", _param0)
	ret0, _ := ret[0].(pkg0.CompiledPackageRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPackageCompilerRecorder) Compile(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Compile", arg0)
}

// Mock of PackageInstaller interface
type MockPackageInstaller struct {
	ctrl     *gomock.Controller
	recorder *_MockPackageInstallerRecorder
}

// Recorder for MockPackageInstaller (not exported)
type _MockPackageInstallerRecorder struct {
	mock *MockPackageInstaller
}

func NewMockPackageInstaller(ctrl *gomock.Controller) *MockPackageInstaller {
	mock := &MockPackageInstaller{ctrl: ctrl}
	mock.recorder = &_MockPackageInstallerRecorder{mock}
	return mock
}

func (_m *MockPackageInstaller) EXPECT() *_MockPackageInstallerRecorder {
	return _m.recorder
}

func (_m *MockPackageInstaller) Install(_param0 pkg0.CompiledPackageRef, _param1 string) error {
	ret := _m.ctrl.Call(_m, "Install", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockPackageInstallerRecorder) Install(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Install", arg0, arg1)
}
