// Code generated by counterfeiter. DO NOT EDIT.
package releasedirfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-cli/releasedir"
)

type FakeConfig struct {
	NameStub        func() (string, error)
	nameMutex       sync.RWMutex
	nameArgsForCall []struct{}
	nameReturns     struct {
		result1 string
		result2 error
	}
	nameReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	DescriptionStub        func() (string, error)
	descriptionMutex       sync.RWMutex
	descriptionArgsForCall []struct{}
	descriptionReturns     struct {
		result1 string
		result2 error
	}
	descriptionReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	LicenseStub        func() (string, error)
	licenseMutex       sync.RWMutex
	licenseArgsForCall []struct{}
	licenseReturns     struct {
		result1 string
		result2 error
	}
	licenseReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	SaveNameStub        func(string) error
	saveNameMutex       sync.RWMutex
	saveNameArgsForCall []struct {
		arg1 string
	}
	saveNameReturns struct {
		result1 error
	}
	saveNameReturnsOnCall map[int]struct {
		result1 error
	}
	BlobstoreStub        func() (string, map[string]interface{}, error)
	blobstoreMutex       sync.RWMutex
	blobstoreArgsForCall []struct{}
	blobstoreReturns     struct {
		result1 string
		result2 map[string]interface{}
		result3 error
	}
	blobstoreReturnsOnCall map[int]struct {
		result1 string
		result2 map[string]interface{}
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeConfig) Name() (string, error) {
	fake.nameMutex.Lock()
	ret, specificReturn := fake.nameReturnsOnCall[len(fake.nameArgsForCall)]
	fake.nameArgsForCall = append(fake.nameArgsForCall, struct{}{})
	fake.recordInvocation("Name", []interface{}{})
	fake.nameMutex.Unlock()
	if fake.NameStub != nil {
		return fake.NameStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.nameReturns.result1, fake.nameReturns.result2
}

func (fake *FakeConfig) NameCallCount() int {
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	return len(fake.nameArgsForCall)
}

func (fake *FakeConfig) NameReturns(result1 string, result2 error) {
	fake.NameStub = nil
	fake.nameReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeConfig) NameReturnsOnCall(i int, result1 string, result2 error) {
	fake.NameStub = nil
	if fake.nameReturnsOnCall == nil {
		fake.nameReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.nameReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeConfig) Description() (string, error) {
	fake.descriptionMutex.Lock()
	ret, specificReturn := fake.descriptionReturnsOnCall[len(fake.descriptionArgsForCall)]
	fake.descriptionArgsForCall = append(fake.descriptionArgsForCall, struct{}{})
	fake.recordInvocation("Description", []interface{}{})
	fake.descriptionMutex.Unlock()
	if fake.DescriptionStub != nil {
		return fake.DescriptionStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.descriptionReturns.result1, fake.descriptionReturns.result2
}

func (fake *FakeConfig) DescriptionCallCount() int {
	fake.descriptionMutex.RLock()
	defer fake.descriptionMutex.RUnlock()
	return len(fake.descriptionArgsForCall)
}

func (fake *FakeConfig) DescriptionReturns(result1 string, result2 error) {
	fake.DescriptionStub = nil
	fake.descriptionReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeConfig) DescriptionReturnsOnCall(i int, result1 string, result2 error) {
	fake.DescriptionStub = nil
	if fake.descriptionReturnsOnCall == nil {
		fake.descriptionReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.descriptionReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeConfig) License() (string, error) {
	fake.licenseMutex.Lock()
	ret, specificReturn := fake.licenseReturnsOnCall[len(fake.licenseArgsForCall)]
	fake.licenseArgsForCall = append(fake.licenseArgsForCall, struct{}{})
	fake.recordInvocation("License", []interface{}{})
	fake.licenseMutex.Unlock()
	if fake.LicenseStub != nil {
		return fake.LicenseStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.licenseReturns.result1, fake.licenseReturns.result2
}

func (fake *FakeConfig) LicenseCallCount() int {
	fake.licenseMutex.RLock()
	defer fake.licenseMutex.RUnlock()
	return len(fake.licenseArgsForCall)
}

func (fake *FakeConfig) LicenseReturns(result1 string, result2 error) {
	fake.LicenseStub = nil
	fake.licenseReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeConfig) LicenseReturnsOnCall(i int, result1 string, result2 error) {
	fake.LicenseStub = nil
	if fake.licenseReturnsOnCall == nil {
		fake.licenseReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.licenseReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeConfig) SaveName(arg1 string) error {
	fake.saveNameMutex.Lock()
	ret, specificReturn := fake.saveNameReturnsOnCall[len(fake.saveNameArgsForCall)]
	fake.saveNameArgsForCall = append(fake.saveNameArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("SaveName", []interface{}{arg1})
	fake.saveNameMutex.Unlock()
	if fake.SaveNameStub != nil {
		return fake.SaveNameStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.saveNameReturns.result1
}

func (fake *FakeConfig) SaveNameCallCount() int {
	fake.saveNameMutex.RLock()
	defer fake.saveNameMutex.RUnlock()
	return len(fake.saveNameArgsForCall)
}

func (fake *FakeConfig) SaveNameArgsForCall(i int) string {
	fake.saveNameMutex.RLock()
	defer fake.saveNameMutex.RUnlock()
	return fake.saveNameArgsForCall[i].arg1
}

func (fake *FakeConfig) SaveNameReturns(result1 error) {
	fake.SaveNameStub = nil
	fake.saveNameReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeConfig) SaveNameReturnsOnCall(i int, result1 error) {
	fake.SaveNameStub = nil
	if fake.saveNameReturnsOnCall == nil {
		fake.saveNameReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveNameReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeConfig) Blobstore() (string, map[string]interface{}, error) {
	fake.blobstoreMutex.Lock()
	ret, specificReturn := fake.blobstoreReturnsOnCall[len(fake.blobstoreArgsForCall)]
	fake.blobstoreArgsForCall = append(fake.blobstoreArgsForCall, struct{}{})
	fake.recordInvocation("Blobstore", []interface{}{})
	fake.blobstoreMutex.Unlock()
	if fake.BlobstoreStub != nil {
		return fake.BlobstoreStub()
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fake.blobstoreReturns.result1, fake.blobstoreReturns.result2, fake.blobstoreReturns.result3
}

func (fake *FakeConfig) BlobstoreCallCount() int {
	fake.blobstoreMutex.RLock()
	defer fake.blobstoreMutex.RUnlock()
	return len(fake.blobstoreArgsForCall)
}

func (fake *FakeConfig) BlobstoreReturns(result1 string, result2 map[string]interface{}, result3 error) {
	fake.BlobstoreStub = nil
	fake.blobstoreReturns = struct {
		result1 string
		result2 map[string]interface{}
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeConfig) BlobstoreReturnsOnCall(i int, result1 string, result2 map[string]interface{}, result3 error) {
	fake.BlobstoreStub = nil
	if fake.blobstoreReturnsOnCall == nil {
		fake.blobstoreReturnsOnCall = make(map[int]struct {
			result1 string
			result2 map[string]interface{}
			result3 error
		})
	}
	fake.blobstoreReturnsOnCall[i] = struct {
		result1 string
		result2 map[string]interface{}
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeConfig) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	fake.descriptionMutex.RLock()
	defer fake.descriptionMutex.RUnlock()
	fake.licenseMutex.RLock()
	defer fake.licenseMutex.RUnlock()
	fake.saveNameMutex.RLock()
	defer fake.saveNameMutex.RUnlock()
	fake.blobstoreMutex.RLock()
	defer fake.blobstoreMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeConfig) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ releasedir.Config = new(FakeConfig)
