// Code generated by counterfeiter. DO NOT EDIT.
package statefakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-agent/v2/agentclient/applyspec"
	"github.com/cloudfoundry/bosh-cli/v7/deployment/instance/state"
)

type FakeState struct {
	CompiledPackagesStub        func() []state.PackageRef
	compiledPackagesMutex       sync.RWMutex
	compiledPackagesArgsForCall []struct {
	}
	compiledPackagesReturns struct {
		result1 []state.PackageRef
	}
	compiledPackagesReturnsOnCall map[int]struct {
		result1 []state.PackageRef
	}
	NetworkInterfacesStub        func() []state.NetworkRef
	networkInterfacesMutex       sync.RWMutex
	networkInterfacesArgsForCall []struct {
	}
	networkInterfacesReturns struct {
		result1 []state.NetworkRef
	}
	networkInterfacesReturnsOnCall map[int]struct {
		result1 []state.NetworkRef
	}
	RenderedJobListArchiveStub        func() state.BlobRef
	renderedJobListArchiveMutex       sync.RWMutex
	renderedJobListArchiveArgsForCall []struct {
	}
	renderedJobListArchiveReturns struct {
		result1 state.BlobRef
	}
	renderedJobListArchiveReturnsOnCall map[int]struct {
		result1 state.BlobRef
	}
	RenderedJobsStub        func() []state.JobRef
	renderedJobsMutex       sync.RWMutex
	renderedJobsArgsForCall []struct {
	}
	renderedJobsReturns struct {
		result1 []state.JobRef
	}
	renderedJobsReturnsOnCall map[int]struct {
		result1 []state.JobRef
	}
	ToApplySpecStub        func() applyspec.ApplySpec
	toApplySpecMutex       sync.RWMutex
	toApplySpecArgsForCall []struct {
	}
	toApplySpecReturns struct {
		result1 applyspec.ApplySpec
	}
	toApplySpecReturnsOnCall map[int]struct {
		result1 applyspec.ApplySpec
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeState) CompiledPackages() []state.PackageRef {
	fake.compiledPackagesMutex.Lock()
	ret, specificReturn := fake.compiledPackagesReturnsOnCall[len(fake.compiledPackagesArgsForCall)]
	fake.compiledPackagesArgsForCall = append(fake.compiledPackagesArgsForCall, struct {
	}{})
	stub := fake.CompiledPackagesStub
	fakeReturns := fake.compiledPackagesReturns
	fake.recordInvocation("CompiledPackages", []interface{}{})
	fake.compiledPackagesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeState) CompiledPackagesCallCount() int {
	fake.compiledPackagesMutex.RLock()
	defer fake.compiledPackagesMutex.RUnlock()
	return len(fake.compiledPackagesArgsForCall)
}

func (fake *FakeState) CompiledPackagesCalls(stub func() []state.PackageRef) {
	fake.compiledPackagesMutex.Lock()
	defer fake.compiledPackagesMutex.Unlock()
	fake.CompiledPackagesStub = stub
}

func (fake *FakeState) CompiledPackagesReturns(result1 []state.PackageRef) {
	fake.compiledPackagesMutex.Lock()
	defer fake.compiledPackagesMutex.Unlock()
	fake.CompiledPackagesStub = nil
	fake.compiledPackagesReturns = struct {
		result1 []state.PackageRef
	}{result1}
}

func (fake *FakeState) CompiledPackagesReturnsOnCall(i int, result1 []state.PackageRef) {
	fake.compiledPackagesMutex.Lock()
	defer fake.compiledPackagesMutex.Unlock()
	fake.CompiledPackagesStub = nil
	if fake.compiledPackagesReturnsOnCall == nil {
		fake.compiledPackagesReturnsOnCall = make(map[int]struct {
			result1 []state.PackageRef
		})
	}
	fake.compiledPackagesReturnsOnCall[i] = struct {
		result1 []state.PackageRef
	}{result1}
}

func (fake *FakeState) NetworkInterfaces() []state.NetworkRef {
	fake.networkInterfacesMutex.Lock()
	ret, specificReturn := fake.networkInterfacesReturnsOnCall[len(fake.networkInterfacesArgsForCall)]
	fake.networkInterfacesArgsForCall = append(fake.networkInterfacesArgsForCall, struct {
	}{})
	stub := fake.NetworkInterfacesStub
	fakeReturns := fake.networkInterfacesReturns
	fake.recordInvocation("NetworkInterfaces", []interface{}{})
	fake.networkInterfacesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeState) NetworkInterfacesCallCount() int {
	fake.networkInterfacesMutex.RLock()
	defer fake.networkInterfacesMutex.RUnlock()
	return len(fake.networkInterfacesArgsForCall)
}

func (fake *FakeState) NetworkInterfacesCalls(stub func() []state.NetworkRef) {
	fake.networkInterfacesMutex.Lock()
	defer fake.networkInterfacesMutex.Unlock()
	fake.NetworkInterfacesStub = stub
}

func (fake *FakeState) NetworkInterfacesReturns(result1 []state.NetworkRef) {
	fake.networkInterfacesMutex.Lock()
	defer fake.networkInterfacesMutex.Unlock()
	fake.NetworkInterfacesStub = nil
	fake.networkInterfacesReturns = struct {
		result1 []state.NetworkRef
	}{result1}
}

func (fake *FakeState) NetworkInterfacesReturnsOnCall(i int, result1 []state.NetworkRef) {
	fake.networkInterfacesMutex.Lock()
	defer fake.networkInterfacesMutex.Unlock()
	fake.NetworkInterfacesStub = nil
	if fake.networkInterfacesReturnsOnCall == nil {
		fake.networkInterfacesReturnsOnCall = make(map[int]struct {
			result1 []state.NetworkRef
		})
	}
	fake.networkInterfacesReturnsOnCall[i] = struct {
		result1 []state.NetworkRef
	}{result1}
}

func (fake *FakeState) RenderedJobListArchive() state.BlobRef {
	fake.renderedJobListArchiveMutex.Lock()
	ret, specificReturn := fake.renderedJobListArchiveReturnsOnCall[len(fake.renderedJobListArchiveArgsForCall)]
	fake.renderedJobListArchiveArgsForCall = append(fake.renderedJobListArchiveArgsForCall, struct {
	}{})
	stub := fake.RenderedJobListArchiveStub
	fakeReturns := fake.renderedJobListArchiveReturns
	fake.recordInvocation("RenderedJobListArchive", []interface{}{})
	fake.renderedJobListArchiveMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeState) RenderedJobListArchiveCallCount() int {
	fake.renderedJobListArchiveMutex.RLock()
	defer fake.renderedJobListArchiveMutex.RUnlock()
	return len(fake.renderedJobListArchiveArgsForCall)
}

func (fake *FakeState) RenderedJobListArchiveCalls(stub func() state.BlobRef) {
	fake.renderedJobListArchiveMutex.Lock()
	defer fake.renderedJobListArchiveMutex.Unlock()
	fake.RenderedJobListArchiveStub = stub
}

func (fake *FakeState) RenderedJobListArchiveReturns(result1 state.BlobRef) {
	fake.renderedJobListArchiveMutex.Lock()
	defer fake.renderedJobListArchiveMutex.Unlock()
	fake.RenderedJobListArchiveStub = nil
	fake.renderedJobListArchiveReturns = struct {
		result1 state.BlobRef
	}{result1}
}

func (fake *FakeState) RenderedJobListArchiveReturnsOnCall(i int, result1 state.BlobRef) {
	fake.renderedJobListArchiveMutex.Lock()
	defer fake.renderedJobListArchiveMutex.Unlock()
	fake.RenderedJobListArchiveStub = nil
	if fake.renderedJobListArchiveReturnsOnCall == nil {
		fake.renderedJobListArchiveReturnsOnCall = make(map[int]struct {
			result1 state.BlobRef
		})
	}
	fake.renderedJobListArchiveReturnsOnCall[i] = struct {
		result1 state.BlobRef
	}{result1}
}

func (fake *FakeState) RenderedJobs() []state.JobRef {
	fake.renderedJobsMutex.Lock()
	ret, specificReturn := fake.renderedJobsReturnsOnCall[len(fake.renderedJobsArgsForCall)]
	fake.renderedJobsArgsForCall = append(fake.renderedJobsArgsForCall, struct {
	}{})
	stub := fake.RenderedJobsStub
	fakeReturns := fake.renderedJobsReturns
	fake.recordInvocation("RenderedJobs", []interface{}{})
	fake.renderedJobsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeState) RenderedJobsCallCount() int {
	fake.renderedJobsMutex.RLock()
	defer fake.renderedJobsMutex.RUnlock()
	return len(fake.renderedJobsArgsForCall)
}

func (fake *FakeState) RenderedJobsCalls(stub func() []state.JobRef) {
	fake.renderedJobsMutex.Lock()
	defer fake.renderedJobsMutex.Unlock()
	fake.RenderedJobsStub = stub
}

func (fake *FakeState) RenderedJobsReturns(result1 []state.JobRef) {
	fake.renderedJobsMutex.Lock()
	defer fake.renderedJobsMutex.Unlock()
	fake.RenderedJobsStub = nil
	fake.renderedJobsReturns = struct {
		result1 []state.JobRef
	}{result1}
}

func (fake *FakeState) RenderedJobsReturnsOnCall(i int, result1 []state.JobRef) {
	fake.renderedJobsMutex.Lock()
	defer fake.renderedJobsMutex.Unlock()
	fake.RenderedJobsStub = nil
	if fake.renderedJobsReturnsOnCall == nil {
		fake.renderedJobsReturnsOnCall = make(map[int]struct {
			result1 []state.JobRef
		})
	}
	fake.renderedJobsReturnsOnCall[i] = struct {
		result1 []state.JobRef
	}{result1}
}

func (fake *FakeState) ToApplySpec() applyspec.ApplySpec {
	fake.toApplySpecMutex.Lock()
	ret, specificReturn := fake.toApplySpecReturnsOnCall[len(fake.toApplySpecArgsForCall)]
	fake.toApplySpecArgsForCall = append(fake.toApplySpecArgsForCall, struct {
	}{})
	stub := fake.ToApplySpecStub
	fakeReturns := fake.toApplySpecReturns
	fake.recordInvocation("ToApplySpec", []interface{}{})
	fake.toApplySpecMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeState) ToApplySpecCallCount() int {
	fake.toApplySpecMutex.RLock()
	defer fake.toApplySpecMutex.RUnlock()
	return len(fake.toApplySpecArgsForCall)
}

func (fake *FakeState) ToApplySpecCalls(stub func() applyspec.ApplySpec) {
	fake.toApplySpecMutex.Lock()
	defer fake.toApplySpecMutex.Unlock()
	fake.ToApplySpecStub = stub
}

func (fake *FakeState) ToApplySpecReturns(result1 applyspec.ApplySpec) {
	fake.toApplySpecMutex.Lock()
	defer fake.toApplySpecMutex.Unlock()
	fake.ToApplySpecStub = nil
	fake.toApplySpecReturns = struct {
		result1 applyspec.ApplySpec
	}{result1}
}

func (fake *FakeState) ToApplySpecReturnsOnCall(i int, result1 applyspec.ApplySpec) {
	fake.toApplySpecMutex.Lock()
	defer fake.toApplySpecMutex.Unlock()
	fake.ToApplySpecStub = nil
	if fake.toApplySpecReturnsOnCall == nil {
		fake.toApplySpecReturnsOnCall = make(map[int]struct {
			result1 applyspec.ApplySpec
		})
	}
	fake.toApplySpecReturnsOnCall[i] = struct {
		result1 applyspec.ApplySpec
	}{result1}
}

func (fake *FakeState) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeState) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ state.State = new(FakeState)
